SmplBB/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SmplBB.views.home', name='home'),
    # url(r'^SmplBB/', include('SmplBB.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', include('core.urls')),

    url(r'^topic/', include('core.urls', namespace='core')),
)

core/urls.py
__author__ = 'Swan'

from django.conf.urls import patterns, include, url
from core import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SmplBB.views.home', name='home'),
    # url(r'^SmplBB/', include('SmplBB.foo.urls')),

    url(r'^$', views.index, name='home'),

    url(r'^(?P<topic_id>\d+)/$', views.topic, name='topic'),

    url(r'^(?P<topic_id>\d+)/reply/$', views.reply, name='reply'),

    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    url(r'^new_topic/post/$', views.new_topic_create, name='new_topic_create'),
)

core/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username=models.CharField(max_length=200)

    def __unicode__(self):
        return self.username


class Topic(models.Model):
    def __unicode__(self):
        return self.title

    author=models.ForeignKey(User)
    title=models.TextField(max_length=2000)
    description=models.TextField(max_length=400)
    pub_date=models.DateTimeField('topic creation date')


class Post(models.Model):
    author=models.ForeignKey(User)
    topic=models.ForeignKey(Topic)
    content=models.TextField(max_length=65535)
    pub_date=models.DateTimeField('post date')

    def __unicode__(self):
        return self.content

core/views.py
# Create your views here.


from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from core.models import Topic, Post, User
from datetime import datetime


def index(request):
    latest_topics = Topic.objects.order_by('-pub_date')

    output = {
        'latest_topics': latest_topics,
    }

    return render(request, 'core/index.html', output)


def topic(request, topic_id):
    displayed_topic = get_object_or_404(Topic, pk=topic_id)
    displayed_post = Post.objects.filter(topic=topic_id).order_by('pub_date')
    return render(request, 'core/topic.html', {'topic': displayed_topic,
                                               'post_list': displayed_post,
    })


def reply(request, topic_id):
    displayed_topic = get_object_or_404(Topic, pk=topic_id)
    displayed_posts = Post.objects.filter(topic=topic_id).order_by('pub_date')
    newreply_content = request.POST['reply_content']
    if not newreply_content:
        error = "Please enter text"
        return render(request, 'core/topic.html', {'topic': displayed_topic,
                                                   'post_list': displayed_posts,
                                                   'error_message': error,
        })
    else:
        newreply = Post(author=displayed_posts[0].author, topic=displayed_topic, content=newreply_content,
                        pub_date=datetime.now())
        newreply.save()
        return HttpResponseRedirect(reverse('core:topic', kwargs={'topic_id': topic_id}))


def new_topic(request):
    return render(request, 'core/new_topic.html')


def new_topic_create(request):
    topic_title = request.POST['new_topic_title']
    topic_description = request.POST['new_topic_description']
    post_content = request.POST['post_content']
    post_author = User.objects.order_by('id')[0]
    if not topic_title:
        error = 'Please enter title'
        return render(request, 'core/new_topic.html', {'error_message': error,
        })
    elif not post_content:
        error = 'Please enter text'
        return render(request, 'core/new_topic.html', {'error_message': error,
        })
    else:
        topic_new = Topic(author=post_author, title=topic_title, description=topic_description, pub_date=datetime.now())
        topic_new.save()
        post = Post(author=post_author, topic=topic_new, content=post_content, pub_date=datetime.now())
        post.save()
        return HttpResponseRedirect(reverse('core:topic', kwargs={'topic_id': topic_new.id}))

core/templates/core/index.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
{% if latest_topics %}
    <table>
    {% for topic in latest_topics %}
        <tr>
        <td><a href="{%  url 'core:topic' topic.id %}">{{ topic.title }}</a></td>
        <td>by <a href="/user/{{ topic.author }}/">{{ topic.author }}</a></td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No topics are available.</p>
{% endif %}

<a href="{% url 'core:new_topic' %}">Create a new thread</a>
</body>
</html>

core/templates/core/new_topic.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<a href="{% url 'core:home' %}">Back</a>
<form action="{% url 'core:new_topic_create' %}" method="post">
{% csrf_token %}
<table border="2">
    <tr>
        <td>
            Topic name:
        </td>
        <td>
            <input type="text" name="new_topic_title">
        </td>
    </tr>
    <tr>
        <td>
            Description:
        </td>
        <td>
            <input type="text" name="new_topic_description">
        </td>
    </tr>
    <tr>
        <td>
            <input type="text" name="post_content">
        </td>
    </tr>
    <tr>
        <td>
            <input type="submit" value="Create topic">
        </td>
    </tr>
</table>
</form>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</body>
</html>

core/templates/core/topic.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
{% if topic %}
    <a href="{% url 'core:home' %}">Back</a>
    <table border="2">
        <tr>
            <td>
            Topic info
            </td>
        </tr>
    <tr><td><table border="1">
        <tr>
        <td>by <a href="/user/{{ topic.author }}/">{{ topic.author }}</td>
        <td>Created: {{ topic.pub_date }}</td>
        </tr>
        <tr>
        <td><h1>{{ topic.title }}</h1></td>
            <td>{{ topic.description }}</td>
        </tr>
    </table></td></tr>
        <tr>
        <td>
        Posts: {{ post_list.count }} total
        </td>
        </tr>
        <tr>
        <td>
            <table border="1">
                {% for post in post_list %}
                    <tr>
                        <h4>
                        <td>by <a href="/user/{{ post.author }}/">{{ post.author }}</a>
                        Date: {{ post.pub_date }}</td>
                        </h4>
                    </tr>
                    <tr>
                        <td>{{ post.content }}</td>
                    </tr>
                {% endfor %}
            </table>
        </td>
        </tr>
    </table>
{% else %}
    <p>No such topic exists.</p>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'core:reply' topic.id %}" method="post">
{% csrf_token %}
    <table>
        <tr>
            <td>Type reply here:</td>
        </tr>
        <tr>
            <td><input type="text" name="reply_content"/></td>
        </tr>
    </table>

<input type="submit" value="Submit" />
</form>
</body>
</html>